CREATE DATABASE g1_GESTFCT
--DROP DATABASE g1_GESTFCT

USE g1_GESTFCT

CREATE TABLE CICLO(
    CODIGOCICLO SMALLINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL
)

CREATE TABLE ALUMNO(
    DNI NVARCHAR(9) PRIMARY KEY,
    TELEFONO NVARCHAR(9) CHECK (TELEFONO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    EMAIL NVARCHAR(50) NOT NULL,
    NOMBRE NVARCHAR(30) NOT NULL,
    APELLIDO1 NVARCHAR(50) NOT NULL,
    APELLIDO2 NVARCHAR(50),
    CODIGOCICLO SMALLINT NOT NULL
)

CREATE TABLE MODULO(
    CODIGOMODULO SMALLINT NOT NULL,
    CODIGOCICLO SMALLINT NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL
)

CREATE TABLE RA(
    NUMERORa SMALLINT NOT NULL,
    CODIGOMODULO SMALLINT NOT NULL,
    CODIGOCICLO SMALLINT NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(100)
)

CREATE TABLE JORNADA(
    FECHA DATETIME NOT NULL,
    DNIALUMNO NVARCHAR(9) NOT NULL,
    HORAS SMALLINT,
    ESTADO NVARCHAR(15) NOT NULL CHECK (ESTADO IN ('PENDIENTE','REALIZADA','CANCELADA'))
)

ALTER TABLE JORNADA
ADD CONSTRAINT DF_FECHA_JORNADA DEFAULT (GETDATE()) FOR FECHA

CREATE TABLE TAREA(
    CODIGOTAREA SMALLINT NOT NULL,
    DNIALUMNO NVARCHAR(9) NOT NULL,
    FECHAJORNADA DATETIME NOT NULL,
    DESCRIPCION NVARCHAR(200) NOT NULL,
    HORAS SMALLINT NOT NULL
)

ALTER TABLE TAREA
ADD CONSTRAINT DF_FECHA_JT DEFAULT GETDATE() FOR FECHAJORNADA

CREATE TABLE RA_TAREA(
    CODIGOTAREA SMALLINT NOT NULL,
    NUMERORA SMALLINT NOT NULL,
    FECHAJORNADA DATETIME NOT NULL,
    CODIGOMODULO SMALLINT NOT NULL,
    DNIALUMNO NVARCHAR(9) NOT NULL,
    CODIGOCICLO SMALLINT NOT NULL
)

ALTER TABLE MODULO
ADD CONSTRAINT PK_MODULO PRIMARY KEY (CODIGOMODULO,CODIGOCICLO)

ALTER TABLE MODULO
ADD CONSTRAINT FK_MODULO_CICLO FOREIGN KEY (CODIGOCICLO)
REFERENCES CICLO(CODIGOCICLO)

ALTER TABLE RA
ADD CONSTRAINT PK_RA PRIMARY KEY (NUMERORA,CODIGOMODULO,CODIGOCICLO)

ALTER TABLE RA
ADD CONSTRAINT FK_RA_MODULO FOREIGN KEY (CODIGOMODULO,CODIGOCICLO)
REFERENCES MODULO(CODIGOMODULO,CODIGOCICLO)

ALTER TABLE ALUMNO
ADD CONSTRAINT FK_ALUMNO_CICLO FOREIGN KEY (CODIGOCICLO)
REFERENCES CICLO(CODIGOCICLO)

ALTER TABLE JORNADA
ADD CONSTRAINT PK_JORNADA PRIMARY KEY (FECHA,DNIALUMNO)

ALTER TABLE JORNADA
ADD CONSTRAINT FK_JORNADA_ALUMNO FOREIGN KEY (DNIALUMNO)
REFERENCES ALUMNO(DNI)

ALTER TABLE TAREA
ADD CONSTRAINT PK_TAREA PRIMARY KEY (CODIGOTAREA,FECHAJORNADA, DNIALUMNO)

ALTER TABLE TAREA
ADD CONSTRAINT FK_TAREA_JORNADA FOREIGN KEY (FECHAJORNADA,DNIALUMNO)
REFERENCES JORNADA(FECHA,DNIALUMNO)

ALTER TABLE RA_TAREA
ADD CONSTRAINT PK_RA_TAREA PRIMARY KEY (CODIGOTAREA,FECHAJORNADA,NUMERORA,CODIGOMODULO,CODIGOCICLO, DNIALUMNO)

ALTER TABLE RA_TAREA
ADD CONSTRAINT FK_RA_TAREA_TAREA FOREIGN KEY (CODIGOTAREA,FECHAJORNADA, DNIALUMNO)
REFERENCES TAREA(CODIGOTAREA,FECHAJORNADA, DNIALUMNO)

ALTER TABLE RA_TAREA
ADD CONSTRAINT FK_RA_TAREA_RA FOREIGN KEY (NUMERORA,CODIGOMODULO,CODIGOCICLO)
REFERENCES RA(NUMERORA,CODIGOMODULO,CODIGOCICLO)

GO
CREATE RULE FECHASRULE AS (@CAMPO<=GETDATE())
GO
EXEC SP_BINDRULE FECHASRULE,'JORNADA.FECHA'
EXEC SP_BINDRULE FECHASRULE,'TAREA.FECHAJORNADA'

GO
CREATE RULE DNISRULE AS (@CAMPO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')
GO
EXEC SP_BINDRULE DNISRULE, 'ALUMNO.DNI'
EXEC SP_BINDRULE DNISRULE, 'JORNADA.DNIALUMNO'
EXEC SP_BINDRULE DNISRULE, 'TAREA.DNIALUMNO'
EXEC SP_BINDRULE DNISRULE, 'RA_TAREA.DNIALUMNO'

GO
CREATE RULE HORASRULE AS (@CAMPO BETWEEN 0 AND 8)
GO
EXEC SP_BINDRULE HORASRULE, 'JORNADA.HORAS'
EXEC SP_BINDRULE HORASRULE, 'TAREA.HORAS'